server:
  port: 60085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.127.241.84:63306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: nomer_admin1
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools:
    restart:
      enabled: false

  thymeleaf:
    cache: false
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true