server:
  port: 60085
  url: http://192.168.0.242:60085
  tomcat:
    accesslog:
     enabled: true              # 액세스 로그 활성화
     pattern: '%h %l %u %t "%r" %s %b %D'  # 액세스 로그 포맷

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.127.241.84:63306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    #url: jdbc:mysql://sinhyeoksu.duckdns.org:3306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: nomer_admin1
    password: 1234
    encryption-key: mySecretKey1234

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: false

  thymeleaf:
    cache: false

  web:
    resources:
      static-locations: /webapp/upload/
      add-mappings: true

  security:
    enabled: false

  main:
    web-application-type: servlet

# health check
management:
  endpoints:
    web:
      exposure:
        include: health,info

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
